.TH PODMOD 5 "October 2022" "podmod.conf" "Podmod"
.SH NAME
podmod \- Configuration file for Podmod.
.SH DESCRIPTION
This is the configuration file for podmod(1).
Neither its presence, nor any of the options, are required.
.PP
This file is an ASCII text file.
Trailing whitespace, lines starting with ‘#’ or ';', and blank lines are ignored.
The format for each option is \fBOPTION=VALUE\fR.
.PP
.SH OPTIONS
.TP
\fBMODULES_DIR\fR \fI\,DIR\/\fR
Search \fI\,DIR\/\fR for the build instructions of the module.
.SH FILES
/etc/podmod.conf
.SH AUTHOR
Written by Alpin H. Gencer <ah@gencer.us>.
.SH "SEE ALSO"
podmod(8)
