.TH PODMOD 8 "October 2022" "podmod v0.3.5" "Podmod"
.SH NAME
podmod \- Containerized build system for kernel modules on Fedora.
.SH SYNOPSIS
.B podmod
[\fI\,OPTIONS\/\fR]
<\fI\,COMMAND\/\fR>
.PP
.B podmod modules
.PP
.B podmod <build|load|unload> -m
<\fI\,MODULE\/\fR>
.SH DESCRIPTION
Builds a kernel module from source inside a Podman container.
Targeted for Fedora Silverblue / Kinoite, but also works for other editions.
.PP
\fBNote:\fR This program must be executed with root privileges.
.SH OPTIONS
.TP
\fB\-\-data\-dir\fR \fI\,DATA_DIR\/\fR
Path to shared architecture-independent files.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information.
.SH SUBCOMMANDS
.TP
\fBbuild\fR
Build the kernel module.
.TP
\fBload\fR
Load the kernel module. The module must already be built for this.
.TP
\fBmodules\fR
List supported kernel modules.
.TP
\fBunload\fR
Unload the kernel module.
.SH AUTHOR
Written by Alpin H. Gencer <ah@gencer.us>.
.SH COPYRIGHT
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
.SH "SEE ALSO"
dkms(8), kmod(8)
.PP
You can download a full copy of the source code at <https://github.com/ahgencer/podmod>.
