.TH PODMOD 8 "October 2022" "podmod v0.3.5" "Podmod"
.SH NAME
podmod \- Containerized build system for kernel modules on Fedora.
.SH SYNOPSIS
.B podmod
[OPTIONS] <SUBCOMMAND>
.PP
.B podmod modules
.PP
.B podmod build
-m <MODULE>
.PP
.B podmod load
-m <MODULE>
.SH DESCRIPTION
Builds a kernel module from source inside a Podman container.
Targeted for Fedora Silverblue / Kinoite, but also works for other editions.
.PP
.B Note:
This program must be executed with root privileges.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR <CONFIG>
Path to the configuration file [default: \fI\,/etc/podmod.conf\/\fP]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
.B build
Build the kernel module
.TP
.B help
Print this message or the help of the given subcommand(s)
.TP
.B load
Load the kernel module
.TP
.B modules
List supported kernel modules
.TP
.B unload
Unload the kernel module
.SH AUTHOR
Written by Alpin H. Gencer <ah@gencer.us>.
.SH COPYRIGHT
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
.SH "SEE ALSO"
podmod.conf(5), dkms(8), kmod(8)
.PP
You can download a full copy of the source code at <https://github.com/ahgencer/podmod>.
