name: Publish package

on:
  push:
    tags:
      - 'rust-podmod-*'

jobs:
  cargo_publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  copr_build:
    name: Build package on Fedora COPR
    runs-on: ubuntu-latest
    needs: cargo_publish
    steps:
      - name: Trigger build with webhook
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.COPR_WEBHOOK_URL }}
