name: Publish package

on:
  push:
    tags:
      - 'rust-podmod-*'

jobs:
  cargo_publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CARGO_REGISTRY_TOKEN}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  copr_build:
    name: Send webhook to start Copr build
    runs-on: ubuntu-latest
    needs: cargo_publish
    steps:
      - run: curl -X POST ${COPR_WEBHOOK_URL}
        env:
          COPR_WEBHOOK_URL: ${{ secrets.COPR_WEBHOOK_URL }}
